export { CanvasStage } from "./CanvasStage";
export { useAwareness } from "./hooks/useAwareness";
export { useRemoteCursors } from "./hooks/useRemoteCursors";
export type { RemoteCursor } from "./hooks/useRemoteCursors";
export { useUndoManager } from "./hooks/useUndoManager";
export { useShapeStore } from "./store/shapeStore";
export type { RealtimeConfig } from "./store/shapeStore";
export { useToolStore } from "./store/toolStore";
export type { ToolOptions } from "./store/toolStore";
export { useAssetStore } from "./store/assetStore";
export { DEFAULT_PAGE_ID } from "./store/pageStore";
export type { ShapeStore } from "./store/shapeStore";
